const GAP_BETWEEN_ARRAY_INDEX_AND_SHEET_ROW = 1;

const FOLDER_ID_STORING_IMAGES = LandGasterId.BMS_FOLDER_ID_STORING_IMAGES();

const SHEET_NAME_1ST = '漫画';
const SHEET_NAME_2ND = '本';
const SHEET_NAME_3RD = '一時ゲット';
const SHEET_NAME_4TH = '紙の';
const SHEET_NAME_5TH = '持っていなくて読みたい本';
const SHEET_NAME_6TH = '2017-2018読んだ';

const COLUMN_INDEX_OF_ID_IN_THE_SHEET = 1;
const COLUMN_INDEX_OF_TITLE  = 2;
const COLUMN_INDEX_OF_IMAGE_URL_DOWNLOADED = 3;
const COLUMN_INDEX_OF_IMAGE_ID_STORED = 4;